name = "PowerWavelet"
uuid = "e18f89e0-c0cd-11e9-07be-897b962ed9be"
authors = ["Losses Don <losses@m-b.science>", "MB Foundation"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[targets]
test = ["Test", "RCall"]
